version: "3.8"
services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: local_db
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: